### PR TITLE
Draft: Fixes for workers to build images from repos

### PR DESCRIPTION
**Pull request by miend**
This contains a fix so that the normal non-standalone worker can execute image builds from repos successfully.

I have been able to test that existing images are successfully pulled and run from both versions of the worker. I've been able to test that both versions of the worker can successfully build an image, too, but I haven't gotten a good candidate to build and run yet.

I would merge #80 before this, because this includes a `mod.json` patch version bump to create new releases.

### CODE REVIEW

**Review by dionjwa — CHANGES_REQUESTED** [review]
I thought the standalone worker doesn't need docker installed. It's only interacting with the remote docker context. Having the docker client is one thing, but building the image within the worker does not feel like the right fix. It feels confusing with the worker-standalone target. I think I need some more understanding here.

**Comment by miend** [comment]
@dionjwa First, a clarification of terms :) "Standalone" refers to the version which does ship its own docker daemon, and is the version which must be capable of running in environments where a docker daemon isn't available. The non-standalone, regular worker is what's getting updated here, and it looks like we're both on the same page there.

As for the change itself, it moves the installation of the docker CLI and associated buildkit plugin to the regular worker, which otherwise didn't have the `docker` command available. The docker daemon is not included in the regular worker by this fix, and remains in the second build stage for the standalone version.

I hope that clears things up.

**Comment by dionjwa** [comment]
Ah right got it, it's actually right there in the install that I didn't see, thanks for the clarification!

**Review by dionjwa — APPROVED** [review]
👍🏻

**Pull request merged**
